version: "3.7"

services:
  elkx-service:
    image: sebp/elkx
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    # restart: unless-stopped
    # volumes:
    #   - ./volumes/elk-data:/var/lib/elasticsearch
    env_file:
      - .env
    networks:
      - legacy
    environment:
      # - ELASTIC_BOOTSTRAP_PASSWORD=${BS_PASSWORD}
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=${PASSWORD}
      - LOGSTASH_USER=logstash_system
      - LOGSTASH_PASSWORD=${PASSWORD}
      - KIBANA_USER=kibana
      - KIBANA_PASSWORD=${PASSWORD}
networks:
  legacy:
    driver: bridge
# /opt/logstash/bin/logstash --path.data /tmp/logstash/data -e 'input { stdin { } } output { elasticsearch { hosts => ["localhost"] } }'
# /opt/logstash/bin/logstash --path.data /tmp/logstash/data -e 'input { stdin { } } output { elasticsearch { hosts => ["localhost"] user => "elastic" password => "changeme" } }'
