version: "3.7"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    restart: unless-stopped
    volumes: 
      - ./src/subCODE:/var/www/
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/sites-enabled/:/etc/nginx/sites-enabled/
    depends_on:
      - php
    networks: 
      - legacy
    environment:
      SERVICE_NAME: nginx
      SERVICE_TAGS: dev
  php:
    build: 
      context: ./php
    ports:
      - 9000:9000
    restart: unless-stopped
    volumes: 
      - ./src/subCODE:/var/www/
    networks: 
      - legacy
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: source_code_v2
      MYSQL_ROOT_PASSWORD: sustcse
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - legacy
  redis:
    image: redis:5.0.5
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - legacy
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./src/subCODE/rabbitmq.config.json:/etc/rabbitmq/rabbitmq.config.json
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - rabbitmqdata:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - legacy
    environment:
      SERVICE_NAME: rabbitmq
      SERVICE_TAGS: dev
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 50:80
    volumes:
     - /sessions
    networks:
      - legacy

networks: 
  legacy:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
  rabbitmqdata:
    driver: local
